GUESS_MSG = "Guess the number from {0} to {1}!"
ATTEMPTS_MSG = "You have {0} attempts"
INPUT_MSG = "_: "
DUMB_MSG = "Are you dumb?"
WIN_MSG = "Congratulation! You won in {0} tries"
LOSE_MSG = "You lose! You used all attempts :("
PLAY_AGAIN_MSG = "Wanna play again?: "